require "rake"
require "rake/testtask"

Rake::TestTask.new do |t|
  t.libs << File.dirname(__FILE__)
  t.test_files = FileList["**/*_test.rb"]
  t.verbose = true
end

desc "Run all tests"
task :default => :test